version: '3'

services:

  proxy:
    build: ../Proxy/
    container_name: proxy
    networks:
      - localnet
    restart: unless-stopped


  crawler:
    build: ../Crawler/
    container_name: crawler
    networks:
      - localnet
    restart: unless-stopped


networks:
  localnet:
    driver: bridge